### PR TITLE
Added custom scrollbar

### PR DESCRIPTION
**Pull request by SaranshBangar**
Resolves issue #85 

Earlier ->

image

Resolved ->

image

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves issue #85

**Comment by afeefuddin** [comment]
The color doesn't look good. The scroll bar looks a bit weird at this state. Try tweaking it a bit.

**Comment by SaranshBangar** [comment]
@afeefuddin sir, I am not sure why but the preview deployment is still showing the older colours, I have changed the colours according to your preference, you can check them in the 'Files changed' section

**Comment by afeefuddin** [comment]
You haven't pushed anything

**Comment by afeefuddin** [comment]
Are you planning to complete this @SaranshBangar ?

**Comment by SaranshBangar** [comment]
@afeefuddin Sir, I have already resolved the issue in this PR

image

**Comment by afeefuddin** [comment]
The colour is the same as the previous one which doesn't looks good. It's unlikely to get quick replies if you don't follow what was suggested.

**Pull request closed without merging**
