### PR TITLE
Added chatbot and Report button in the dashboard

### PR DESCRIPTION
**Pull request by ronisarkarexe**
Added chatbot and Report button in the dashboard

fixed issue #40

### CODE REVIEW

**Comment by afeefuddin** [comment]
Please upload Screenshots of the changes.

**Comment by afeefuddin** [comment]
We don't want to remove the Dashboard button from the homepage, we just want to remove it from the Dashboard page, you might need to create a new component for that.

**Comment by ronisarkarexe** [comment]
> We don't want to remove the Dashboard button from the homepage, we just want to remove it from the Dashboard page, you might need to create a new component for that.

is there a new component that will be added under the dashboard? and design for new component like header?

**Comment by ronisarkarexe** [comment]
> Please upload Screenshots of the changes.

chat
report

**Comment by ronisarkarexe** [comment]
> > We don't want to remove the Dashboard button from the homepage, we just want to remove it from the Dashboard page, you might need to create a new component for that.
> 
> is there a new component that will be added under the dashboard? and design for new component like header?

Could you please clarify what you mean by, like when we click Dashboard, then show this two button?

**Comment by afeefuddin** [comment]
No,
We want these two buttons only in the /dashboard route.
In the other routes we want the old button `dashboard` only .

**Comment by ronisarkarexe** [comment]
> No, We want these two buttons only in the `/dashboard` route. In the other routes we want the old button `dashboard` only .

Okay, thank you for explaining.

**Comment by ronisarkarexe** [comment]
> > No, We want these two buttons only in the `/dashboard` route. In the other routes we want the old button `dashboard` only .
> 
> Okay, thank you for explaining.

img1
img2

@afeefuddin please review it.

**Comment by algovengers** [comment]
What will I review, you haven't made any changes since last commit. Please don't tag maintainers until you're sure that you're PR is ready for review.

**Comment by afeefuddin** [comment]
What will I review, you haven't made any changes since last commit. Please don't tag maintainers until you're sure that you're PR is ready for review.

**Comment by afeefuddin** [comment]
This is not what I intended but seems okay, can you add a header so that Users know that the lower section of the dashboard is showing previous reports.

Add *Your Reports*

**Comment by ronisarkarexe** [comment]
> This is not what I intended but seems okay, can you add a header so that Users know that the lower section of the dashboard is showing previous reports.
> 
> Add _Your Reports_

in the dashboard section, have one new header, that holds both buttons right?

**Comment by afeefuddin** [comment]
Not really. For now you can add a header "your reports" above the  reports which are displayed

**Comment by afeefuddin** [comment]
Are you planning to complete this?

**Comment by ronisarkarexe** [comment]
> Are you planning to complete this?

btn

**Comment by afeefuddin** [comment]
As I suggested, please add a header to show that below options visible are your past reports.

**Pull request closed without merging**
