### PR TITLE
Add Toast Notifications

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
#72 
image

### CODE REVIEW

**Comment by afeefuddin** [comment]
I think we only need toast notifications of successful login/signup and maybe failed login/signup

**Comment by Rohitha-pudu** [comment]
> I think we only need toast notifications of successful login/signup and maybe failed login/signup

providing for all will be a good user experience

**Comment by afeefuddin** [comment]
No, we are planning to add those messages in the login form, instead of giving toast notifications. There are other PRs working on that. It would be nice if you make necessary changes.

**Comment by Rohitha-pudu** [comment]
> No, we are planning to add those messages in the login form, instead of giving toast notifications. There are other PRs working on that. It would be nice if you make necessary changes.

they were in the login form only

**Pull request closed without merging**
