### PR TITLE
Navbar UI updated at Fix/issue- #103

### PR DESCRIPTION
**Pull request by SnehansuBehera**
The Navbar is fixed and made responsive for mobile screens, hamburger menu is added for buttons n navbar for mobile screens
issue #103 is fixed.

### CODE REVIEW

**Comment by SnehansuBehera** [comment]
Screenshot 2024-05-18 005343
Screenshot (367)
Screenshot (368)

**Comment by afeefuddin** [comment]
The dropdown menu looks unappealing. Should we reduce the size of the buttons to fix it? Will that work?

**Comment by afeefuddin** [comment]
For now we should reduce the button size. The dropdown menu is even looking worse at the current state with that design

**Comment by SnehansuBehera** [comment]
Screenshot 2024-05-26 181307

does it look good @afeefuddin

**Comment by SnehansuBehera** [comment]
@afeefuddin added pr

**Comment by afeefuddin** [comment]
We can't merge this for several reasons.
1) You have a merge commit 
2) Your commits aren't squashed
3) Most of your changes are just linting the file (which is ok but shouldn't be done hear)

**Comment by afeefuddin** [comment]
Are you planning to fix this @SnehansuBehera?

**Comment by afeefuddin** [comment]
Closing this since it has been stale for a long time.

**Pull request closed without merging**
