### PR TITLE
Loaders added for fetching chats with AI

### PR DESCRIPTION
**Pull request by atharvarekhawar**
#41  Add a loader in chatbot when the user is waiting for response issue is solved by this Pull request

### CODE REVIEW

**Comment by atharvarekhawar** [comment]
I created a new branch and pushed my changes with single commit , plz merge this PR @afeefuddin

**Comment by afeefuddin** [comment]
The button to send message should be disabled when the history is being fetched. It would be great if you can fix that. Otherwise LGTM.

**Comment by atharvarekhawar** [comment]
@afeefuddin I can fix it but again there will be a problem of squashing commits, what to do?

**Comment by afeefuddin** [comment]
No don't open too many PRs for a single issue, spend sometime learning about git and github.

**Comment by atharvarekhawar** [comment]
@afeefuddin  I am able to squash the commits locally but then it is not letting me push without rebase and then all commits are back in the local

**Comment by atharvarekhawar** [comment]
@afeefuddin done with the squashing , you can now merge the PR .

**Comment by afeefuddin** [comment]
LGTM, Merged thanks @atharvarekhawar

**Pull request merged**
