### PR TITLE
Login Error Message

### PR DESCRIPTION
**Pull request by Omsurvase24**
This is the issue #83 . When I tried to login with incorrect password or email it showed error 401 which was not friendly for the common user. And also in other cases it just showed Network Error. 

I switched up the frontend code so now when someone tries to login with incorrect password and email, It will say that either the Password or email that I have entered is incorrect. And in other cases it will show that some error has occurred, please try again.

NOTE : To set the project locally I renamed .env.sample to .env as it was written in the Readme file and have pushed those changes.

### CODE REVIEW

**Comment by algovengers** [comment]
Yes but you should undo during PR. 
Currently .env.sample is deleted in your PR. You have to fix that.

**Comment by afeefuddin** [comment]
That was a bit mistake from our side, you should undo the deletion of  `.env.sample`

**Comment by Omsurvase24** [comment]
#83 Hey I did the undo of the deletion of the .env.sample file now as you said.
You can check the pull request again now.

**Comment by afeefuddin** [comment]
Squash both the commits

**Comment by Omsurvase24** [comment]
Hey I did squash the commits. It is now just one commit. 
Should be done now.
Thanks for being patient with me.

**Comment by afeefuddin** [comment]
Recent changes to login page UI has introduced  merge conflicts to this PR. You need to rebase it with upstream/main.

**Comment by afeefuddin** [comment]
You have to rebase the branches instead of merging them.

**Pull request closed without merging**
