### PR TITLE
Added a Confirm Password button. in Harify/frontend/src/app/signup/page.tsx file.

### PR DESCRIPTION
**Pull request by akshaydubey05**
**ISSUE:**-#95

- Added a new **Confrm Password** button in the Harify/frontend/src/app/signup/page.tsx file. 

- I also added the functionality that if passwords are not matching, an error message will display.

_(also added minor changes)_

### CODE REVIEW

**Comment by akshaydubey05** [comment]
Clears issue #95 .

**Comment by afeefuddin** [comment]
Heads up @akshaydubey05. We have merged some PRs that have introduced merge conflicts to your PR. You need to rebase your  PR from upstream/main

**Comment by akshaydubey05** [comment]
Ok i will do it .

**Comment by akshaydubey05** [comment]
- Hi, @afeefuddin ,I have made desired changes; please view them. If any issue still arises, please tell me.

_(Actually, I am a beginner and am trying to learn new things. Sorry for the issues .)_

**Comment by afeefuddin** [comment]
Great work as a beginner. Merged, thanks @akshaydubey05.

**Comment by akshaydubey05** [comment]
thanks @afeefuddin  😊

**Pull request merged**
