### PR TITLE
Update page.tsx

### LINKED ISSUE #195: Feat : Update footer
Want to update footer by adding a dynamic copyright year section that will auto fetch the current year

### PR DESCRIPTION
**Pull request by Meetjain1**
Closes #195 

### Description:
This PR enhances the footer section of the website by adding the current copyright year, which is fetched dynamically. This ensures that the copyright year will always be up-to-date without requiring manual updates each year.

#### Changes:
1. **Footer HTML**: Updated the footer to include a placeholder for the copyright year.
2. **JavaScript**: Added a script to fetch the current year dynamically and insert it into the footer.
3. **CSS**: Ensured that the styling of the footer remains consistent with the new dynamic content.

#### Benefits:
- **Automation**: The copyright year updates automatically, reducing maintenance overhead.
- **Accuracy**: Ensures the displayed year is always current, improving the website's professionalism.

### CODE REVIEW

**Comment by Meetjain1** [comment]
@afeefuddin please review this pr. Thanks

**Comment by Meetjain1** [comment]
> @afeefuddin please review this pr. Thanks

@afeefuddin

**Comment by Meetjain1** [comment]
@afeefuddin

**Comment by Meetjain1** [comment]
@afeefuddin please review this pr . Gssoc is ending tomorrow please review before this. Thanks

**Comment by afeefuddin** [comment]
Spammy PR, no one asked for.

**Comment by Meetjain1** [comment]
> Spammy PR, no one asked for.

Yeah , Good morning 
and bye

**Pull request closed without merging**
