### PR TITLE
Loader added while chatting with AI

### PR DESCRIPTION
**Pull request by atharvarekhawar**
#41  Add a loader in chatbot when the user is waiting for response issue is solved by this Pull request

### CODE REVIEW

**Comment by afeefuddin** [comment]
Please add a loader when we are fetching history of the chat also.

**Comment by atharvarekhawar** [comment]
loader_chat

@afeefuddin should I push the code?

**Comment by afeefuddin** [comment]
Yes and squash both the commits into one.

**Comment by atharvarekhawar** [comment]
@afeefuddin done with the commit

**Comment by afeefuddin** [comment]
Please squash both the commits

**Comment by atharvarekhawar** [comment]
@afeefuddin I am unable to squash the commits , should I create a fresh PR

**Comment by afeefuddin** [comment]
You can refer to this [squashing a commit](https://www.freecodecamp.org/news/git-squash-commits/)

**Comment by atharvarekhawar** [comment]
Actually I tried doing it earlier but things messed up, I am thinking of closing this PR and creating a new one from a new branch , is that ok with you ? @afeefuddin

**Pull request closed without merging**
