### PR TITLE
Feat : Add contributors section

### LINKED ISSUE #197: Feat : Add contributors section
want to add contributors in readme.md file .

### PR DESCRIPTION
**Pull request by Meetjain1**
Closes #197 

Added contributors profile in readme.md

### CODE REVIEW

**Comment by Meetjain1** [comment]
@afeefuddin please review this pr. Thanks

**Comment by Meetjain1** [comment]
> @afeefuddin please review this pr. Thanks

@afeefuddin

**Comment by Meetjain1** [comment]
> > @afeefuddin please review this pr. Thanks
> 
> @afeefuddin

@afeefuddin please review

**Comment by Meetjain1** [comment]
@afeefuddin please review this pr

**Comment by Meetjain1** [comment]
> @afeefuddin please review this pr

@afeefuddin

**Comment by Meetjain1** [comment]
@afeefuddin please review this pr . Gssoc is ending tomorrow please review before this. Thanks

**Comment by afeefuddin** [comment]
PR had no use. We don't review unnecessary PR just for the sake of it.

**Comment by Meetjain1** [comment]
> PR had no use. We don't review unnecessary PR just for the sake of it.

Good Morning , 
Oh nice @afeefuddin I see your activeness highly appreciating. Thanks and bye

**Pull request closed without merging**
