### PR TITLE
Added link to the bottom credit reference

### LINKED ISSUE #143: Github handle missing at the bottom of credit reference
WhatsApp Image 2024-05-24 at 10 25 55_2236d6c3

In the "Made by Algovengers" at the bottom, the github handle is not provided, so there's no way to access the handle from the deployed website.

Can you kindly assign this issue to me under GSSOC 2024?

### PR DESCRIPTION
**Pull request by DarkAngelu**
Fixes #143 

This PR adds a link to the bottom credit reference to this own repository.

### CODE REVIEW

**Comment by afeefuddin** [comment]
Squash all the commits.

**Comment by DarkAngelu** [comment]
Done

**Comment by afeefuddin** [comment]
You have made a merge commit, please squash or revert the merge commit.

**Comment by DarkAngelu** [comment]
Done

**Comment by DarkAngelu** [comment]
Hey can I open a new Pull Request for the same issue. To be honest I'm having quite the trouble to merge/squash all these comments into one. My Endsem Exams are also going on, that's why I'm really not able to give time in this.

**Comment by afeefuddin** [comment]
This have some merge commits being squashed in the original one. Create a new PR

**Pull request closed without merging**
